steps:
  - name: gcr.io/cloud-builders/gradle
    entrypoint: bash
    args:
      - "./gradlew"
      - "build"
      - "-Ptag=$TAG_NAME"
  - name: bash
    args:
      - 'ls'
      - '-alh'
      - './build/distributions'