steps:
  - name: debian:buster-slim
    env:
      - 'ORG_GRADLE_PROJECT_version=fake-tag'
    entrypoint: "/bin/echo"
    args:
      - "$ORG_GRADLE_PROJECT_version"
  - name: debian:buster-slim
    entrypoint: "/bin/echo"
    args:
      - "$TAG_NAME"